### ISSUE TITLE
@AuthenticationPrincipal Member member 에서 member가 null 로 조회되는 문제

### ISSUE THREAD

**Issue by seowonn** [2024TeamUnity/Goods_BE#13]
## 설명
___

- 회원 탈퇴 기능 구현 중 @AuthenticationPrincipal Member member 로 member 정보를 받아오는데 null로 조회됨
- UserDetailsImpl / loadUserByUsername / jwtTokenProvider 쪽으로 수정이 필요할 듯
- 세부로직 보면서 해결 과정 기록하기는 용으로 남김

**Comment by channnoh** [comment]
@AuthenticationPrincipal UserDetailsImpl member 로 해보시겠어요??

**Comment by seowonn** [comment]
아 Principal이 loadUserByUsername의 반환값을 캐치하는 거라 해당 메소드 반환 형태인 UserDetailsImpl로 받아야 하는군요!!
감사합니다!
