### ISSUE TITLE
Feat: 배포 환경 조사

### ISSUE THREAD

**Issue by seowonn** [2024TeamUnity/Goods_BE#23]
## 설명
* 도커 이미지, mysql DB, 배포 과정 조사
* 내용 학습 후 배포 진행 

## 기능
___

**Comment by channnoh** [comment]
@seowonn 지금 aws랑 rds 생성 했고, git action 작성 하고 테스트 해보려고 하고 있습니다!

**Comment by seowonn** [comment]
앗 이제 봤네요.. 넵 알겠습니다! 저는 도커쪽 알아보고 있었습니다! ec2 배포는 언제 진행할지 내일 논의해봅시다!
